name: Actions HostRun
description: Run host commands when there is container defined in job
author: ArhatDev
inputs:
  shell:
    required: false
    description: Same as job.<job-id>.steps.shell
    default: sh
  run:
    required: true
    description: Same as job.<job-id>.steps.run
    default: ""
  nsenter1-image:
    required: false
    description: Docker image of https://github.com/justincormack/nsenter1
    default: justincormack/nsenter1
outputs:
  stdout:
    description: stdout output of command execution
  stderr:
    description: stderr output of command execution
runs:
  using: node12
  main: dist/index.js
