name: Actions HostRun
description: Run host commands when there is container defined in job
author: ArhatDev
inputs:
  shell:
    required: false
    description: Same as job.<job-id>.steps.shell
    default: bash
  run:
    required: true
    description: Same as job.<job-id>.steps.run
    default: ""
  working-directory:
    required: false
    description: Same as job.<job-id>.steps.working-directory
    default: ""
runs:
  using: node12
  main: dist/index.js
